Agregando primer fichero index html y css.
luiscodmi/onei-tools pull request #1
Opened 2024-01-06 19:47 UTC by luiscodmi

aqui pongo todo lo que se me ocurra hasta imagenes.

2024-01-06 20:53 UTC, leosbelpoll requested changes
Esta muy bien para el primer disenno profesional!!

No te pongas triste por los 25 comentarios ejjej, es normal al inicio hasta que se te vayan pegando las buenas practicas, ya luego no vas cometiendo los mismos errores

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    display: inline;
para que esta linea?

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    font-family: 'Courier New', Courier, monospace;
generalmente ponemos el font family en el `body`, pero no en el selector universal, el `margin` si tiene sentido que este ahi, porque quieres darselo a cada elemento por separado, NO el margin del body solamente

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.header * {
por que una clase header y un elemento header? ya con el elemento es suficiente, la clase con lo mismo no aporta nada

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.header * {
No hace falta el `*` para la fuente, solo poniendoselo al elemento todo dentro de el lo agarra

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    width: 100vw;
cuando  `display: block` (el default de los contenedores)(siendo el header un contenedor) no necesitamos poner `width: 100vw` porque los contenedores son de tipo bloque y se agarran todo el ancho. Lo que paso fue que pusiste `display: inline` y se dejo de comportar como bloque (arriba te pregunto el proposito)

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    align-items: center;
`align-items` solo trabaja con `display: flex`, no debe estar haciendo nada aca esa linea

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.div-header {
`.div-header`, `header`, `.header` jejej muchos nombres para lo mismo, los nombres deben dar la idea solo de leerlos para que son

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.info-perfil, p, b {
cuando agregas `, p, b` al selector significa que para todos los `p` y las `b` de la pagina se va a aplicar, es lo que quieres? no estaria mal, solo se ve raro que mezcles en el mismo selector a la `.info-perfil` (que es especifico) y a elementos generales

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.aside {
eso es la clase `aside`? si es correcto no aporta nada ese nombre, el mismo comentario del header

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    font-size: 16px;
```suggestion
    font-size: 1rem;
```

es lo mismo (cuando nadie ha cambiado el tamanno por defecto es `16px`

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.search-aside {
no mezcles elementos de html en los nombres de clases, los nombres tienen que decir que es el elemento, no que elemento de html es, ex: `.search` con eso ya estaria bien, a menos que hayan varios search y quieras especificar con otra cosa, pero no cosas de html

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    margin-bottom: .3rem;
estas dos propiedades son contrarias, una empuja a la otra en el lado opuesto, con solo una basta, solo tienes que ponerle el valor adecuado

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    border: 0;
cuando quieres que una propiedad no tenga nada de nada el valor que se usa normalmente es `none`, `0` seria para cosas puramente numericas, ex: `margin: 0`, pero `border` recibe el tipo, el color, el tamanno, etc, en ese caso es mas normal usar `none`

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.input::after { /* aquí fue donde traté de hacer el pico (la punta) del buscador */
esto lo vemos luego, es un tin mas avanzado. Lo otro, esos comentarios no lo subas en el codigo, o sino comentalo todo si no esta funcionando, lo normal es que no subas nada, y que tengas una tarea dedicada solamente a eso

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.search-main {
ahora vi que habian dos search, por el disenno, los nombres me suenan mas a

`search-menu` `search`

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    background: yellow;
solo para que tengas en cuenta
no es muy buena practica usar los nombres que vienen por defecto ... pero ... si en tu disenno se ve perfecto, entonces esta perfectamente bien

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +.div-content-page {
```suggestion
.content {
```

content es suficiente, el `div` esta de mas y la `pagina` tambien

2024-01-06 20:53 UTC, leosbelpoll commented on index.css
> +    position: fixed;
me resulta curioso esto 🤔 por que esto esta fijo?

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +    <title>Index: ONEI tools</title>
```suggestion
    <title>ONEI Tools</title>
```

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +    <header class="header">
```suggestion
    <header>
```

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +    </header>
el `header` creo que no quedo bien estructurado, creo que seria algo asi para que no tengas elementos con nombres innecesarios

```html
<header>
    <p>ONEI│tools</p>
    <div class="info-perfil">
      <p> <b>Perfil:</b> Administrator</p>
      <p>ROLE_ADMIN</p>
      <p>_ Salir</p>
    </div>
</header>
<nav class="breadcrumb">Inicio /</nav>
```

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +        <aside class="aside">
```suggestion
        <aside class="main-menu">
```

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +    <div class="div-content-page">
```suggestion
    <div class="content">
```

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +        <input type="search" name="" id="" class="search-main" placeholder="_ ¿Qué le gustaría buscar?">
si no tienen valor no se ponen
```suggestion
        <input type="search" class="search-main" placeholder="_ ¿Qué le gustaría buscar?" />
```

2024-01-06 20:53 UTC, leosbelpoll commented on index.html
> +            <input type="search" name="" id="aside-input" class="search-aside" placeholder="_ Buscar">
```suggestion
            <input type="search" id="aside-input" class="search-aside" placeholder="_ Buscar" />
```

2024-01-12 03:20 UTC, luiscodmi commented on index.css
> +    display: inline;
debe haber sido algo que se me quedó!!

2024-01-12 03:23 UTC, luiscodmi commented on index.css
> +    font-family: 'Courier New', Courier, monospace;
y por qué necesariamente en el body???, para ahorrar recursos o algo parecido???

2024-01-12 03:31 UTC, luiscodmi commented on index.css
> +.header * {
pero si paso las propiedades de una hacia la otra se jode la interfaz; tendría que volver a trabajar en ello (supongo que tengas razón, jejeje y no sea una pregunta trampa).
Fue algo que fui probando y se me quedó!

2024-01-12 03:40 UTC, luiscodmi commented on index.css
> +.header * {
Pues pruebo y se me desajusta, (según lo que entendí que me dices);
entonces lo hago así: (que ahora mismo busqué y no veo como poner el codigo en monospace)
header * {
    font-family: Arial, Helvetica, sans-serif;
    /* display: inline; */
    width: 100vw;
    font-size: 3.5rem;
    align-items: center;
    white-space: nowrap;
} 
y se me desaparaece el lado derecho de la cabecera. Supongo que también tenfria que reconstruirlo para trabajar más limpio.

2024-01-12 03:44 UTC, luiscodmi commented on index.css
> +    width: 100vw;
ah ya!!!

2024-01-12 03:49 UTC, luiscodmi commented on index.html
> +        <aside class="aside">
es fue más por no estar pensando en tantos nombres, (como las variables jejeje)

2024-01-12 03:52 UTC, luiscodmi commented on index.html
> +        <input type="search" name="" id="" class="search-main" placeholder="_ ¿Qué le gustaría buscar?">
jajaja, es que yo se los dejo así para "recordarme" que salen así por defecto; manías que le salen a uno programando.
Ya lo sé y lo trataré de recordar pa la próxima!!

2024-01-16 04:34 UTC, luiscodmi commented on index.css
> +    font-family: 'Courier New', Courier, monospace;
esta fue una de las cosas que dabatimos por el cell, que comprendí y ya la arreglé también!

2024-01-16 05:59 UTC, leosbelpoll commented on index.html
> +        <aside class="aside">
esto no fue resuelto, voy a "unresolve conversation"

2024-01-16 06:02 UTC, leosbelpoll requested changes
Aun quedan cosas por resolver, fijate que hay algo que dice X conversaciones ocultas, si les das click te las muestra

imagen
<img width="876" alt="image" src="https://github.com/luiscodmi/onei-tools/assets/43287334/38f0cd6b-2c5e-4590-87a6-069da8fbebb4">


Tambien le di a **no resolver** un comentario `<aside class="aside" ....` que le diste resolver pero vi que no se trabajo en eso

2024-01-16 20:09 UTC, luiscodmi commented on index.css
> +    align-items: center;
Bueno, ya esto desapareció con algun arreglo de los anteriores o algun cambio que hice, porque ya ya está display: flex. Creo que fue cuando puse el cuadrado blanco al lado de la info para alguna foto o algo parecido, que tuve que hacer uso de eso

2024-01-16 20:11 UTC, luiscodmi commented on index.css
> +.info-perfil, p, b {
esto ya lo arreglé. Me sucedio en principio por acabarlo, y despues tambien pense que en algun momento iba hacer ilógico

2024-01-16 20:12 UTC, luiscodmi commented on index.css
> +    font-size: 16px;
jejeje esto no se como se me fue!!; si desde que vi tu clase no he hecho mas uso de px

2024-01-16 21:02 UTC, luiscodmi commented on index.html
> +        <aside class="aside">
ya está OK!!

2024-01-16 21:06 UTC, luiscodmi commented on index.css
> +.div-header {
ya lo acotejé!!; como .main-header

2024-01-16 21:15 UTC, luiscodmi commented on index.css
> +.aside {
ya está hecho!!; main-menu; aunque la verdad me hubiese gustado main-aside, para adaptarme a tener tantas definiciones en cuenta.

2024-01-16 21:17 UTC, luiscodmi commented on index.css
> +.search-aside {
en este caso de html si tengo 2 search; además que lo hago para manejar mejor los elementos que tengo en el html.

2024-01-16 21:45 UTC, luiscodmi commented on index.css
> +    margin-bottom: .3rem;
es que quiero con eso separar el search de arriba con el nav-header (que está muy pegado, y le quita espacio), y de abajo para tratarle de dar el mismo espacio entre ellos. Lo que no quería es ponerle x x x x para sus cuatro lados.
Estoy al tanto de cualquier otra aclaración más específica.

2024-01-16 21:46 UTC, luiscodmi commented on index.css
> +    border: 0;
ok!!

2024-01-16 21:54 UTC, luiscodmi commented on index.css
> +    background: yellow;
no no, ya lo cambié!!, le puse class = "a-link" para tener bien identificado cuando crezca más el código; además que tú sabes lo que me gusta poner como clase el elemento de HTML y algo más para recordar mejor.

2024-01-16 21:55 UTC, luiscodmi commented on index.css
> +.div-content-page {
ok!, ya le puse container

2024-01-16 22:01 UTC, luiscodmi commented on index.css
> +    position: fixed;
Jejeje, eso se me quedó ahí, por alguna prueba o algo que traté de hacer.
Lo que me resulta curioso a mí, jajaja es cómo te diste cuenta de eso (solo una línea entre tantas); supongo que con el tiempo se gane experiencia y se lea mejor el código como un metodología jejeje.
Gracias por revisar! y ayudarme!

2024-01-16 22:57 UTC, luiscodmi commented on index.html
> +    <title>Index: ONEI tools</title>
Esas son tonterías que me caen!

2024-01-16 22:58 UTC, luiscodmi commented on index.html
> +    <header class="header">
Ya lo resolví con main-header o al revés.

2024-01-16 23:27 UTC, luiscodmi commented on index.html
> +            <input type="search" name="" id="aside-input" class="search-aside" placeholder="_ Buscar">
Ya esto -sino me equivoco- lo resolví!!

2024-01-17 01:32 UTC, leosbelpoll approved these changes
Genial! Seguimos avanzando!!

2024-01-17 01:32 UTC, leosbelpoll commented on index.css
> +    margin-bottom: .3rem;
mala mia aqui, no se porque habia leido algo negativo, entonces pense que estabas "alando" espacio en sentidos contrario, pero son valores positivos, es decir que estas empujandolo de los otros. Todo bien!

2024-01-17 01:32 UTC, leosbelpoll commented on index.css
> +    background: yellow;
aquí me estaba refiriendo al color `yellow`, tienes que fijarte la linea donde esta el comentario jejej, pero esto es menor, solo fijarte que el amarillo por defecto se vea bien

2024-01-18 02:36 UTC, luiscodmi commented on index.css
> +    background: yellow;
ah ya ok!!; no había caído en eso!! de que se trataba del color jejeje

2024-02-13 23:10 UTC, merged